from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path

from .radar_config import LIGHT_SPEED_M_S


@dataclass(frozen=True)
class StudioLuaConfig:
    com_port: int = 12
    baudrate: int = 921600
    connect_timeout_ms: int = 1000
    sop_control: int = 2
    power_on_mode: int = 1
    mmwave_studio_root: str = r"C:\ti\mmwave_studio_02_01_01_00\mmWaveStudio"
    capture_path: str = r"C:\ti\mmwave_studio_02_01_01_00\mmWaveStudio\PostProc\adc_data.bin"
    host_ip: str = "192.168.33.30"
    dca_ip: str = "192.168.33.180"
    dca_mac: str = "12:34:56:78:90:12"
    config_port: int = 4096
    data_port: int = 4098
    packet_delay_us: int = 25
    start_freq_ghz: float = 77.0
    idle_time_us: float = 120.0
    adc_start_us: float = 0.0
    ramp_end_us: float = 51.3
    slope_mhz_us: float = 77.8
    adc_samples: int = 256
    sample_rate_ksps: int = 5000
    rx_gain_db: int = 30
    chirp_loops: int = 16
    frame_count: int = 5
    frame_period_ms: float = 100.0

    def metrics(self) -> dict[str, float | int]:
        adc_time_s = self.adc_samples / (self.sample_rate_ksps * 1e3)
        sampled_bandwidth_hz = self.slope_mhz_us * 1e12 * adc_time_s
        range_resolution_m = LIGHT_SPEED_M_S / (2.0 * sampled_bandwidth_hz)
        return {
            "adc_time_us": adc_time_s * 1e6,
            "sampled_bandwidth_hz": sampled_bandwidth_hz,
            "range_resolution_m": range_resolution_m,
            "max_range_m": (self.sample_rate_ksps * 1e3) * LIGHT_SPEED_M_S / (2.0 * self.slope_mhz_us * 1e12),
            "chirps_per_frame": self.chirp_loops,
            "frames": self.frame_count,
        }

    def as_dict(self) -> dict[str, float | int | str]:
        return asdict(self)


def _lua_string(value: str | Path) -> str:
    text = str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def _lua_number(value: float | int) -> str:
    if isinstance(value, int):
        return str(value)
    if value.is_integer():
        return str(int(value))
    return f"{value:.12g}"


def generate_iwr1843_studio_lua(config: StudioLuaConfig | None = None) -> str:
    cfg = config or StudioLuaConfig()
    mmwave_root = _lua_string(cfg.mmwave_studio_root)
    capture_path = _lua_string(cfg.capture_path)
    metrics = cfg.metrics()

    return f"""-- Generated by mmwavelab-dca1000.
-- Target: TI IWR1843 + AR-DevPack/FTDI + DCA1000 raw ADC capture.
-- Path: mmWave Studio firmware-load route, not mmWave SDK demo CLI route.
-- User hardware note: physical SOP was reported as 1 0 0 on 2026-04-29.
-- Studio logical SOPControl remains configurable; default is {cfg.sop_control}.
--
-- Range profile:
--   start frequency: {cfg.start_freq_ghz} GHz
--   slope: {cfg.slope_mhz_us} MHz/us
--   ADC samples: {cfg.adc_samples}
--   sample rate: {cfg.sample_rate_ksps} ksps
--   sampled bandwidth: {metrics["sampled_bandwidth_hz"] / 1e9:.6f} GHz
--   theoretical range resolution: {metrics["range_resolution_m"] * 1000:.2f} mm/bin

COM_PORT = {cfg.com_port}
BAUDRATE = {cfg.baudrate}
CONNECT_TIMEOUT_MS = {cfg.connect_timeout_ms}
SOP_MODE = {cfg.sop_control}
POWER_ON_MODE = {cfg.power_on_mode}

MMWAVE_STUDIO_ROOT = {mmwave_root}
FW_ROOT = MMWAVE_STUDIO_ROOT .. "\\\\..\\\\rf_eval_firmware"
BSS_FW = FW_ROOT .. "\\\\radarss\\\\xwr18xx_radarss.bin"
MSS_FW = FW_ROOT .. "\\\\masterss\\\\xwr18xx_masterss.bin"
SAVE_DATA_PATH = {capture_path}

HOST_IP = "{cfg.host_ip}"
DCA_IP = "{cfg.dca_ip}"
DCA_MAC = "{cfg.dca_mac}"
CONFIG_PORT = {cfg.config_port}
DATA_PORT = {cfg.data_port}
PACKET_DELAY_US = {cfg.packet_delay_us}

START_FREQ = {_lua_number(cfg.start_freq_ghz)}
IDLE_TIME = {_lua_number(cfg.idle_time_us)}
ADC_START_TIME = {_lua_number(cfg.adc_start_us)}
RAMP_END_TIME = {_lua_number(cfg.ramp_end_us)}
FREQ_SLOPE = {_lua_number(cfg.slope_mhz_us)}
ADC_SAMPLES = {cfg.adc_samples}
SAMPLE_RATE = {cfg.sample_rate_ksps}
RX_GAIN = {cfg.rx_gain_db}
CHIRP_LOOPS = {cfg.chirp_loops}
FRAME_COUNT = {cfg.frame_count}
FRAME_PERIOD_MS = {_lua_number(cfg.frame_period_ms)}

function mmwl_call(label, fn)
    local ok, ret = pcall(fn)
    if ok == false then
        WriteToLog(label .. " exception: " .. tostring(ret) .. "\\n", "red")
        return -9999
    end
    if ret == 0 then
        WriteToLog(label .. " Success\\n", "green")
    else
        WriteToLog(label .. " failure, ret=" .. tostring(ret) .. "\\n", "red")
    end
    return ret
end

WriteToLog("mmwavelab IWR1843+DCA1000 Studio capture script start\\n", "green")

mmwl_call("FullReset", function() return ar1.FullReset() end)
RSTD.Sleep(1000)
mmwl_call("SOPControl", function() return ar1.SOPControl(SOP_MODE) end)
RSTD.Sleep(1000)
connect_ret = mmwl_call("Connect", function() return ar1.Connect(COM_PORT, BAUDRATE, CONNECT_TIMEOUT_MS) end)
if connect_ret ~= 0 then
    WriteToLog("Aborting before firmware download because Connect failed on COM" .. tostring(COM_PORT) .. "\\n", "red")
    return
end
connected_ret = mmwl_call("Calling_IsConnected", function() return ar1.Calling_IsConnected() end)
if connected_ret ~= 0 then
    WriteToLog("Aborting before firmware download because Calling_IsConnected failed on COM" .. tostring(COM_PORT) .. "\\n", "red")
    return
end
ar1.frequencyBandSelection("77G")
ar1.SelectChipVersion("XWR1843")

mmwl_call("DownloadBSSFw", function() return ar1.DownloadBSSFw(BSS_FW) end)
mmwl_call("DownloadMSSFw", function() return ar1.DownloadMSSFw(MSS_FW) end)
mmwl_call("PowerOn", function() return ar1.PowerOn(POWER_ON_MODE, 1000, 0, 0) end)
mmwl_call("RfEnable", function() return ar1.RfEnable() end)

mmwl_call("ChanNAdcConfig", function() return ar1.ChanNAdcConfig(1, 1, 0, 1, 1, 1, 1, 2, 1, 0) end)
mmwl_call("LPModConfig", function() return ar1.LPModConfig(0, 0) end)
mmwl_call("RfInit", function() return ar1.RfInit() end)
RSTD.Sleep(1000)

mmwl_call("DataPathConfig", function() return ar1.DataPathConfig(1, 1, 0) end)
mmwl_call("LvdsClkConfig", function() return ar1.LvdsClkConfig(1, 1) end)
mmwl_call("LVDSLaneConfig", function() return ar1.LVDSLaneConfig(0, 1, 1, 0, 0, 1, 0, 0) end)

mmwl_call("ProfileConfig", function() return ar1.ProfileConfig(
    0, START_FREQ, IDLE_TIME, ADC_START_TIME, RAMP_END_TIME,
    0, 0, 0, 0, 0, 0, FREQ_SLOPE, 0,
    ADC_SAMPLES, SAMPLE_RATE, 0, 0, RX_GAIN
) end)
mmwl_call("ChirpConfig", function() return ar1.ChirpConfig(0, 0, 0, 0, 0, 0, 0, 1, 0, 0) end)
mmwl_call("FrameConfig", function() return ar1.FrameConfig(0, 0, FRAME_COUNT, CHIRP_LOOPS, FRAME_PERIOD_MS, 0, 0, 1) end)

mmwl_call("SelectCaptureDevice", function() return ar1.SelectCaptureDevice("DCA1000") end)
mmwl_call("CaptureCardConfig_EthInit", function() return ar1.CaptureCardConfig_EthInit(HOST_IP, DCA_IP, DCA_MAC, CONFIG_PORT, DATA_PORT) end)
mmwl_call("CaptureCardConfig_Mode", function() return ar1.CaptureCardConfig_Mode(1, 2, 1, 2, 3, 30) end)
mmwl_call("CaptureCardConfig_PacketDelay", function() return ar1.CaptureCardConfig_PacketDelay(PACKET_DELAY_US) end)

mmwl_call("CaptureCardConfig_StartRecord", function() return ar1.CaptureCardConfig_StartRecord(SAVE_DATA_PATH, 1) end)
RSTD.Sleep(1000)
mmwl_call("StartFrame", function() return ar1.StartFrame() end)
RSTD.Sleep(FRAME_COUNT * FRAME_PERIOD_MS + 2000)

WriteToLog("mmwavelab capture script done. ADC target: " .. SAVE_DATA_PATH .. "\\n", "green")
"""


def write_iwr1843_studio_lua(path: str | Path, config: StudioLuaConfig | None = None) -> StudioLuaConfig:
    cfg = config or StudioLuaConfig()
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generate_iwr1843_studio_lua(cfg), encoding="utf-8")
    return cfg
